/**
 * Inventory: product categories and products.
 * Matches the Inventory page design (stats, table, "Add Category" and
 * "Add Product" forms). Adjust field names here to match the NestJS DTOs
 * once the backend exists — every inventory component reads through these.
 */

export type CategoryStatus = "ACTIVE" | "INACTIVE";
export type ProductStatus = "ACTIVE" | "INACTIVE" | "DRAFT";
export type StockStatus =
  | "IN_STOCK"
  | "LOW_STOCK"
  | "OUT_OF_STOCK"
  | "ACTIVE"
  | "INACTIVE"
  | "DRAFT";

/** A row in the "Product Categories" list (image 4). */
export type Category = {
  id: string;
  name: string;
  description?: string;
  /** Path/URL of the uploaded category image, if any */
  image?: string | null;
  status: CategoryStatus;
  /** Position in the storefront category list */
  displayOrder: number;
  /** How many products currently use this category (read-only, server-computed) */
  productCount: number;
  createdAt: string;
  updatedAt: string;
};

export type CreateCategoryRequest = {
  name: string;
  description?: string;
  /** File, when the form includes a new image; omit to keep/skip */
  image?: File | null;
  status: CategoryStatus;
  displayOrder: number;
};

export type UpdateCategoryRequest = Partial<CreateCategoryRequest> & {
  id: string;
};

/**
 * A product can either stand alone or be the parent of variants (e.g. sizes),
 * matching the "Variant Option" field on the New Product form.
 */
export type VariantOption = "NONE" | "PARENT" | "VARIENT";

export type ProductVariant = {
  id: string;
  /** e.g. "500g", "1kg" */
  label: string;
  sku: string;
  unitPrice: number;
  stock: number;
};

/** A row in the Inventory product table (image 1). */
export type Product = {
  id: string;
  /** Auto-generated by the backend, e.g. "PRD-0016" */
  productId: string;
  name: string;
  description?: string;
  images?: string[] | null;
  categoryId: string;
  category: Pick<Category, "id" | "name">;
  sku: string;
  variantOption: VariantOption;
  variants?: ProductVariant[];
  /** Unit of measurement, e.g. "pc", "kg", "bag", "tray" */
  unitType: string;
  unitPrice: number;
  /** Optional weight, in the unit the backend expects (e.g. kg) */
  weight?: number | null;
  stock: number;
  /** Stock level that should trigger a "Low Stock" status */
  reorderLevel: number;
  stockStatus: StockStatus;
  status: ProductStatus;
  tags: string[];
  displayOrder?: number;
  updatedAt: string;
  createdAt: string;
};

export type CreateProductRequest = {
  variantOption: VariantOption;
  name: string;
  categoryId: string;
  description?: string;
  images?: File[] | null;
  displayOrder?: number;
  unitType: string;
  unitPrice: number;
  weight?: number | null;
  stock: number;
  reorderLevel: number;
  status: ProductStatus;
  tags?: string[];
};

export type UpdateProductRequest = Partial<CreateProductRequest> & {
  id: string;
};

/** Query params for the product table: search, filters, sort and pagination. */
export type ListProductsParams = {
  /** Matches the "Search using order id......" box (searches name/SKU/ID) */
  search?: string;
  categoryId?: string;
  status?: ProductStatus;
  stockStatus?: StockStatus;
  page?: number;
  perPage?: number;
  sortBy?: "name" | "stock" | "unitPrice" | "updatedAt";
  sortDir?: "asc" | "desc";
};

export type Paginated<T> = {
  items: T[];
  total: number;
  page: number;
  perPage: number;
};

/** The four numbers at the top of the Inventory page. */
export type InventoryStats = {
  totalProducts: { value: number; changePercent?: number };
  inStock: { value: number; change?: number };
  lowStock: { value: number; changePercent?: number };
  outOfStock: { value: number; change?: number };
};
